//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetarDecoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MetarDecoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cloud and visiblity OK.
        /// </summary>
        internal static string CAVOK {
            get {
                return ResourceManager.GetString("CAVOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dew point.
        /// </summary>
        internal static string DewPoint {
            get {
                return ResourceManager.GetString("DewPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        internal static string ForICAO {
            get {
                return ResourceManager.GetString("ForICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to released.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gusting to.
        /// </summary>
        internal static string Gusting {
            get {
                return ResourceManager.GetString("Gusting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to knots.
        /// </summary>
        internal static string knots {
            get {
                return ResourceManager.GetString("knots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metar information.
        /// </summary>
        internal static string MetarInfo {
            get {
                return ResourceManager.GetString("MetarInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to meter(s).
        /// </summary>
        internal static string meters {
            get {
                return ResourceManager.GetString("meters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous significant weather.
        /// </summary>
        internal static string PreviousWeather {
            get {
                return ResourceManager.GetString("PreviousWeather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runways.
        /// </summary>
        internal static string RunwayConditions {
            get {
                return ResourceManager.GetString("RunwayConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertical visibility.
        /// </summary>
        internal static string VerticalVisibility {
            get {
                return ResourceManager.GetString("VerticalVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string Visibility {
            get {
                return ResourceManager.GetString("Visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind from.
        /// </summary>
        internal static string WindFrom {
            get {
                return ResourceManager.GetString("WindFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wind speed.
        /// </summary>
        internal static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vary between.
        /// </summary>
        internal static string WindVaryingBetween {
            get {
                return ResourceManager.GetString("WindVaryingBetween", resourceCulture);
            }
        }
    }
}
